FROM amazonlinux:2

LABEL org.opencontainers.image.source="https://github.com/neilmunday/slurm-mail" \
      org.opencontainers.image.description="An Amazon Linux 2 Slurm container intended for testing Slurm-Mail" \
      org.opencontainers.image.title="amzn2-slurm" \
      maintainer="Neil Munday"

ARG SLURM_VER=25.11.2
ARG MARIADB_VER=11.4

# download, build, install and clean-up
RUN yum update -y && \
    amazon-linux-extras install epel -y && \
    rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB && \
    yum install -y yum-utils && \
    yum-config-manager --add-repo https://yum.mariadb.org/${MARIADB_VER}/rhel7-amd64 && \
    yum install -y \
      autoconf \
      automake \
      gcc \
      mailx \
      make \
      MariaDB-devel \
      MariaDB-client \
      MariaDB-server \
      munge-devel \
      pam-devel \
      perl \
      perl-ExtUtils-MakeMaker \
      python3 \
      readline-devel \
      rpm-build \
      supervisor \
      tini \
      wget && \
    wget https://download.schedmd.com/slurm/slurm-${SLURM_VER}.tar.bz2 -O /root/slurm-${SLURM_VER}.tar.bz2 && \
    rpmbuild -tb /root/slurm-${SLURM_VER}.tar.bz2 && \
    yum localinstall -y /root/rpmbuild/RPMS/x86_64/slurm-${SLURM_VER}*.amzn2.x86_64.rpm \
    /root/rpmbuild/RPMS/x86_64/slurm-slurmctld-${SLURM_VER}*.amzn2.x86_64.rpm \
    /root/rpmbuild/RPMS/x86_64/slurm-slurmd-${SLURM_VER}*.amzn2.x86_64.rpm \
    /root/rpmbuild/RPMS/x86_64/slurm-slurmdbd-${SLURM_VER}*.amzn2.x86_64.rpm && \
    yum -y erase \
      autoconf \
      automake \
      gcc \
      MariaDB-devel \
      munge-devel \
      pam-devel \
      readline-devel \
      rpm-build \
      wget && \
    yum clean all && \
    rm -rf /root/rpmbuild /root/slurm*.tar.bz2 && \
    groupadd -r slurm && \
    useradd -r -g slurm -d /var/empty/slurm -m -s /bin/bash slurm && \
    groupadd test && \
    useradd -g test -d /home/test -m test && \
    install -d -o slurm -g slurm /etc/slurm /var/spool/slurm /var/log/slurm && \
    dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key 2>/dev/null && \
    chown munge:munge /etc/munge/munge.key && \
    chmod 0400 /etc/munge/munge.key

COPY supervisord.conf /etc/
COPY --chown=slurm slurm.*.conf /etc/slurm/
COPY --chown=slurm slurmdbd.conf /etc/slurm/
COPY --chown=slurm cgroup.conf /etc/slurm/
COPY --chown=root entrypoint.sh /usr/local/sbin/

RUN MAJOR_VER=`echo ${SLURM_VER} | egrep -o "^[0-9]+"` && \
  mv /etc/slurm/slurm.${MAJOR_VER}.conf /etc/slurm/slurm.conf && \
  rm -f /etc/slurm/slurm.*.conf && \
  chmod 600 /etc/slurm/slurm*.conf

RUN /usr/bin/mariadb-install-db --user=mysql

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/sbin/entrypoint.sh"]
CMD ["tail -f /dev/null"]
