FROM centos:7

LABEL org.opencontainers.image.source="https://github.com/neilmunday/slurm-mail" \
      org.opencontainers.image.description="A CentOS 7 Slurm container intended for testing Slurm-Mail" \
      org.opencontainers.image.title="centos7-slurm" \
      maintainer="Neil Munday"

ARG SLURM_VER=24.11.1

# Note: CentOS 7 is EOL so we have to make use of vault repos
COPY CentOS-Base.repo /etc/yum.repos.d/
COPY CentOS-7.9.repo /etc/yum.repos.d/

# download, build, install and clean-up
RUN yum update -y && \
    yum install -y epel-release && \
    yum install -y \
      autoconf \
      automake \
      gcc \
      mailx \
      make \
      mariadb-devel \
      mariadb-server \
      munge-devel \
      pam-devel \
      perl \
      perl-ExtUtils-MakeMaker \
      python3 \
      readline-devel \
      rpm-build \
      supervisor \
      tini \
      wget && \
    wget https://download.schedmd.com/slurm/slurm-${SLURM_VER}.tar.bz2 -O /root/slurm-${SLURM_VER}.tar.bz2 && \
    rpmbuild -tb /root/slurm-${SLURM_VER}.tar.bz2 && \
    yum localinstall -y /root/rpmbuild/RPMS/x86_64/slurm-${SLURM_VER}*.el7.x86_64.rpm \
    /root/rpmbuild/RPMS/x86_64/slurm-slurmctld-${SLURM_VER}*.el7.x86_64.rpm \
    /root/rpmbuild/RPMS/x86_64/slurm-slurmd-${SLURM_VER}*.el7.x86_64.rpm \
    /root/rpmbuild/RPMS/x86_64/slurm-slurmdbd-${SLURM_VER}*.el7.x86_64.rpm && \
    yum -y erase \
      autoconf \
      automake \
      gcc \
      mariab-devel \
      make \
      munge-devel \
      pam-devel \
      readline-devel \
      rpm-build \
      wget && \
    yum clean all && \
    rm -rf /root/rpmbuild /root/slurm*.tar.bz2 && \
    groupadd -r slurm && \
    useradd -r -g slurm -d /var/empty/slurm -m -s /bin/bash slurm && \
    groupadd test && \
    useradd -g test -d /home/test -m test && \
    install -d -o slurm -g slurm /etc/slurm /var/spool/slurm /var/log/slurm && \
    dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key 2>/dev/null && \
    chown munge:munge /etc/munge/munge.key && \
    chmod 0400 /etc/munge/munge.key

COPY supervisord.conf /etc/
COPY --chown=slurm slurm.*.conf /etc/slurm/
COPY --chown=slurm slurmdbd.conf /etc/slurm/
COPY --chown=root entrypoint.sh /usr/local/sbin/

RUN MAJOR_VER=`echo ${SLURM_VER} | egrep -o "^[0-9]+"` && \
  mv /etc/slurm/slurm.${MAJOR_VER}.conf /etc/slurm/slurm.conf && \
  rm -f /etc/slurm/slurm.*.conf && \
  chmod 600 /etc/slurm/slurm*.conf

RUN /usr/bin/mysql_install_db --user=mysql

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/sbin/entrypoint.sh"]
CMD ["tail -f /dev/null"]
