FROM opensuse/leap:15.5

LABEL org.opencontainers.image.source="https://github.com/neilmunday/slurm-mail" \
      org.opencontainers.image.description="A OpenSuSE 15 Slurm container intended for testing Slurm-Mail" \
      org.opencontainers.image.title="opensuse8-slurm" \
      maintainer="Neil Munday"

ARG SLURM_VER=23.11.3
ARG MARIADB_VER=11.3

RUN zypper update -y && \
    rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB && \
    zypper addrepo --gpgcheck --refresh https://yum.mariadb.org/${MARIADB_VER}/sles/15/x86_64 mariadb && \
    zypper --gpg-auto-import-keys refresh && \
    zypper install -y \
    gcc \
    MariaDB-devel \
    MariaDB-client \
    MariaDB-server \
    mailx \
    munge-devel \
    pam-devel \
    perl \
    python3 \
    python3-setuptools \
    readline-devel \
    rpm-build \
    tar \
    supervisor \
    tini \
    wget && \
    wget https://download.schedmd.com/slurm/slurm-${SLURM_VER}.tar.bz2 -O /root/slurm-${SLURM_VER}.tar.bz2 && \
    rpmbuild -tb /root/slurm-${SLURM_VER}.tar.bz2 && \
    zypper install --allow-unsigned-rpm -y \
    /usr/src/packages/RPMS/x86_64/slurm-${SLURM_VER}*.x86_64.rpm \
    /usr/src/packages/RPMS/x86_64/slurm-slurmctld-${SLURM_VER}*.x86_64.rpm \
    /usr/src/packages/RPMS/x86_64/slurm-slurmd-${SLURM_VER}*.x86_64.rpm \
    /usr/src/packages/RPMS/x86_64/slurm-slurmdbd-${SLURM_VER}*.x86_64.rpm && \
    zypper remove -y \
    gcc \
    MariaDB-devel \
    make \
    munge-devel \
    pam-devel \
    readline-devel \
    rpm-build \
    wget && \
    zypper clean && \
    rm -vrf /usr/src/packages/* && \
    groupadd -r slurm && \
    useradd -r -g slurm -d /var/empty/slurm -m -s /bin/bash slurm && \
    groupadd test && \
    useradd -g test -d /home/test -m test && \
    install -d -o slurm -g slurm /etc/slurm /var/spool/slurm /var/log/slurm && \
    rm -rfv /root/slurm*

COPY supervisord.conf /etc/
COPY --chown=slurm slurm.*.conf /etc/slurm/
COPY --chown=slurm slurmdbd.conf /etc/slurm/
COPY --chown=root entrypoint.sh /usr/local/sbin/

RUN MAJOR_VER=`echo ${SLURM_VER} | egrep -o "^[0-9]+"` && \
    mv /etc/slurm/slurm.${MAJOR_VER}.conf /etc/slurm/slurm.conf && \
    rm -f /etc/slurm/slurm.*.conf && \
    chmod 600 /etc/slurm/slurm*.conf && \
    /usr/bin/mariadb-install-db --user=mysql && \
    ln -s /tini /usr/bin/tini && \
    ln -s /var/log/supervisord /var/log/supervisor && \
    ln -s /usr/bin/mariadb /usr/bin/mysql && \
    ln -s /usr/bin/mariadbd-safe /usr/bin/mysqld_safe

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/sbin/entrypoint.sh"]
CMD ["tail -f /dev/null"]
