name: Pylint

on:
  pull_request:
    paths:
      - '.github/workflows/pylint.yml'
      - 'supported_python_versions.json'
      - '**.py'
  push:
    paths:
      - '.github/workflows/pylint.yml'
      - 'supported_python_versions.json'
      - '**.py'
  workflow_dispatch:

jobs:
  generate_python_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        name: set-matrix
        run: |
          matrix=$(cat ./supported_python_versions.json)
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
  lint:
    needs: generate_python_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{fromJson(needs.generate_python_matrix.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiosmtpd
        pip install bs4
        pip install pylint
        pip install pytest
        pip install PyYAML
        pip install requests
        pip install setuptools
        pip install typing-extensions
    - name: Remove too-many-positional-arguments if Python < 3.9
      run: |
        sed -i 's/too-many-positional-arguments,//' $(git ls-files '*.py')
      if: ${{ matrix.python-version == '3.6' || matrix.python-version == '3.7' || matrix.python-version == '3.8' }}
    - name: Analysing the code with pylint for Python 3.6
      run: |
        pylint --disable=duplicate-code,no-self-use $(git ls-files '*.py')
      if: ${{ matrix.python-version == '3.6' }}
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
      if: ${{ matrix.python-version != '3.6' }}
